# This is a basic workflow to help you get started with Actions

name: claim
on:
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch:
jobs:
  claim:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: curl -L "https://ipv4.games/claim?name=squarebowl.club"
